[player]
origin = [0.0, 65.62, 0.0]
fovy = 90.0
speed = 25.0
sensitivity = 0.0025
render_distance = 36

[sky]
sun_intensity = 15.0

[sky.day]
intensity = [1.0, 1.0, 1.0]
color = [0.25, 0.53, 1.0]
horizon_color = [0.37, 0.62, 1.0]

[sky.night]
intensity = [0.15, 0.15, 0.3]
color = [0.0, 0.0, 0.0]
horizon_color = [0.025, 0.025, 0.04]

[sky.object]
size = 0.1

[sky.star]
size = 0.005
brightness = 0.15
count = 1500

[cloud]
day_opacity = 0.9915
night_opacity = 0.85
speed = 100.0

[gui.crosshair]
size = 1.0

[gui.inventory]
content = ["glowstone", "glass_magenta", "glass_cyan"]
size = 2.25
