[player]
origin = [0.0, 65.62, 0.0]
fovy = 90.0
speed = 25.0
sensitivity = 0.0025
render_distance = 16

[sky]
sun_intensity = 15.0

[sky.day]
color = [0.22, 0.5, 1.0]
horizon_color = [0.37, 0.62, 1.0]
light_intensity = [1.0, 1.0, 1.0]

[sky.night]
color = [0.0, 0.0, 0.0]
horizon_color = [0.02, 0.02, 0.03]
light_intensity = [0.1, 0.1, 0.25]

[sky.object]
size = 0.1

[sky.star]
size = 0.005
brightness = 0.15
count = 1500

[cloud]
speed = 1.0

[cloud.day]
color = [1.0, 1.0, 1.0, 0.99]

[cloud.night]
color = [0.06, 0.06, 0.1, 0.85]

[gui.crosshair]
size = 1.0

[gui.inventory]
content = ["glowstone", "glass_magenta", "glass_cyan", "dead_bush"]
size = 2.25
