diagonal = [1.0, 1.0, 1.0]

[[side_corner_deltas.front]]
lower_left = [0, 0, 0]
lower_right = [1, 0, 0]
upper_right = [1, 1, 0]
upper_left = [0, 1, 0]

[[side_corner_deltas.right]]
lower_left = [1, 0, 0]
lower_right = [1, 0, 1]
upper_right = [1, 1, 1]
upper_left = [1, 1, 0]

[[side_corner_deltas.back]]
lower_left = [1, 0, 1]
lower_right = [0, 0, 1]
upper_right = [0, 1, 1]
upper_left = [1, 1, 1]

[[side_corner_deltas.left]]
lower_left = [0, 0, 1]
lower_right = [0, 0, 0]
upper_right = [0, 1, 0]
upper_left = [0, 1, 1]

[[side_corner_deltas.top]]
lower_left = [0, 1, 0]
lower_right = [1, 1, 0]
upper_right = [1, 1, 1]
upper_left = [0, 1, 1]

[[side_corner_deltas.bottom]]
lower_left = [0, 0, 1]
lower_right = [1, 0, 1]
upper_right = [1, 0, 0]
upper_left = [0, 0, 0]
