g = 0.7
sun_intensity = [40.0, 40.0, 40.0]
h_ray = 8e3
b_ray = [5.5e-6, 13.0e-6, 22.4e-6]
h_mie = 1.2e3
b_mie = [21e-6, 21e-6, 21e-6]
h_ab = 30e3
b_ab = [2.04e-5, 4.97e-5, 1.95e-6]
ab_falloff = 4e3
r_planet = 6371e3
r_atmosphere = 6471e3
num_samples = 32
num_light_samples = 8
