g = 0.76
sun_intensity = [20.0, 20.0, 20.0]
h_ray = 8e3
b_ray = [5.8e-6, 13.5e-6, 33.1e-6]
h_mie = 1.2e3
b_mie = [21e-6, 21e-6, 21e-6]
r_planet = 6371e3
r_atmosphere = 6471e3
n_samples = 16
n_light_samples = 8
