[air]
light_filter = [1.0, 1.0, 1.0]

[grass]
atlas_coords.front = [3, 0]
atlas_coords.right = [3, 0]
atlas_coords.back = [3, 0]
atlas_coords.left = [3, 0]
atlas_coords.up = [0, 0]
atlas_coords.down = [2, 0]

[glowstone]
atlas_coords.front = [9, 6]
atlas_coords.right = [9, 6]
atlas_coords.back = [9, 6]
atlas_coords.left = [9, 6]
atlas_coords.up = [9, 6]
atlas_coords.down = [9, 6]
luminance = [15, 15, 0]
