[air]
light_filter = [1.0, 1.0, 1.0]

[grass]
tex_coords.front = [3, 0]
tex_coords.right = [3, 0]
tex_coords.back = [3, 0]
tex_coords.left = [3, 0]
tex_coords.up = [0, 0]
tex_coords.down = [2, 0]

[glowstone]
tex_coords.front = [9, 6]
tex_coords.right = [9, 6]
tex_coords.back = [9, 6]
tex_coords.left = [9, 6]
tex_coords.up = [9, 6]
tex_coords.down = [9, 6]
luminance = [15, 15, 0]
